data:
  build: ./docker/data
  volumes:
    - ./shared:/shared
    - ./app:/var/www/app
    - /var/www/app/vendor
    - /var/www/app/bin
    - /var/www/app/app/cache
    - /var/www/app/app/logs

nginx:
  build: ./docker/nginx
  ports:
   - "80:80"
  links:
   - php
  volumes_from:
    - data

php:
  build: ./docker/php
  links:
   - mysql:db
  volumes_from:
    - data

mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_USER: app
    MYSQL_PASSWORD: apppassword
    MYSQL_DATABASE: app
